### ISSUE TITLE
The font looks blurred

### ISSUE THREAD

**Issue by vada-pav** [datafunk/NNW-newsjunkie-theme#1]
Tried the theme. The background is decent colour. However, the font is blurred and I am finding it difficult to read
![Screenshot 2022-04-25 at 8 59 38 PM](https://user-images.githubusercontent.com/59252456/165122225-5bb7b2bd-fa8c-4c2b-8ac0-a4633577c26b.png)
.

**Comment by datafunk** [comment]
Yes, you're right, I realised that too. This is an ultra light font, so will look at tweaking it a bit over the weekend. - Thanks for having a go at it!

**Comment by vada-pav** [comment]
![Screenshot 2022-04-29 at 1 07 37 PM](https://user-images.githubusercontent.com/59252456/165902988-6013eeac-f411-423b-ad99-4dd2c1e36a8c.png)

I created this using your theme as a reference.

**Comment by datafunk** [comment]
Looks good, I probably like it more than mine :)
Either way if I get a couple of hours this w/e I'll fiddle a bit more. I just upped the font-weight (of a thicker variant) and now it's too bright again. You've got the balance right, but I like the look of those very lightweight fonts, except for the issue you mentioned originally.

**Comment by vada-pav** [comment]
If the background is too dark and the font is light, it makes it difficult to read. I read about it somewhere.
So, i made the background not too dark and font not too light.

I'd be happy to work with you on this or other things or maybe learn from you.
I'm new to this and don't have much knowledge.

**Comment by datafunk** [comment]
I think the problem lied in having the "ultra light" font variant and sub pixel rendering. I didn't investigate, but noticed the difference between a Retina display and my mid range acer screen. I'm waiting for the iOS update as that's where I read most of my news.

You're very kind, but  I am not a designer. I reckon you've more to learn from what's out there.
I take accessibility (a11y) seriously though.

By the way you can learn heaps from doing a11y checks, e.g. by using Lighthouse in devtools etc. It's really evolved these days, giving you contrast scores etc straight out of the box.

I took inspiration from your design to offset the thicker font with a slightly darker font colour :)

**Comment by datafunk** [comment]
Resolved by 9d95c8f696f6a199b53ab040de45f95a6867c212
